---
version: "2.1"

services:
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: unless-stopped
    volumes:
      - ./telegraf:/etc/telegraf/:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - 8125:8125

  influxdb:
    image: influxdb:1.8-alpine
    restart: unless-stopped
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - /data/influxdb:/var/lib/influxdb:rw
    ports:
      - 8086:8086

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: unless-stopped
    volumes:
      - /data/grafana:/var/lib/grafana:rw
    depends_on:
      - influxdb
    links:
      - influxdb   
    ports:
      - 3000:3000
